#!/bin/bash
# 2019-10-03 Jani Janttari <janttari@yandex.ru>
# Purkaa transport streamista ensin tekstityksen kuviksi, sitten käsittelee kuvatparemmin ocr tunnistettaviksi,
# tunnistaa kuvista tekstin tekstitiedostoiksi ja lopulta kutsuu python-skriptiä joka luo srt-tiedoston
#
temppiHakemisto="/tmp/dvbteksti2srt"
projektiNimi="dvbteksti2srt"
omaSijainti=$PWD
usage(){
    echo "Käyttö:"
    echo "$0 filename"
    echo "$0 -lang=swe filename"
    exit 1
}

# parseroidaan arrgumentit jos niitä on
kieli=fin #oletuskielenä on suomi, jos argumentteinä ei muuta määrätä
fontti="norm" #oletusfontti. Tällä määritellään convertin parametrejä myöhemmin
luku=0 #argumenttien määrän laskuri
for var in "$@" #Käydään läpi kaikki argumentit
do
    if [[ $var == -lang* ]] ; then #jos  argumenttina on määritelty haluttu kieli
        kieli=$(echo $var|cut -f 2 -d "=") #  argumentti esim -lang=swe -->swe
    fi
    
    if [[ $var == -font* ]] ; then #jos ekana argumenttina on määritelty haluttu fontti
        fontti=$(echo $var|cut -f 2 -d "=") #  argumentti esim -font=oma
    fi
    
    ((luku++))
done

if [[ "$fontti" == "norm" ]] ; then convertParametrit="-set colorspace Gray -separate -average  -alpha off -negate"; fi
if [[ "$fontti" == "testi1" ]] ; then convertParametrit="-negate -alpha remove -background black"; fi

vtiedosto=$var # viimeisenä (tai ainoana) argumenttinä on tiedoston nimi
# ---------------------------------------------------------------------------
tessekieli="-l $kieli" #välitetään tesseractille kieli esim "-l swe"
#fi

is_file_exits(){
    local f="$vtiedosto"
    [[ -f "$f" ]] && return 0 || return 1
}
[[ $# -eq 0 ]] && usage

if !( is_file_exits "$vtiedosto" )
then
 echo "Tiedostoa ei ole, seis!"
 exit
fi
# ********************************* LUODAAN TEMPPI HAKEMISTO ********************************************************
if ! [ -d "$temppiHakemisto" ]; then #jos dvbteksti2srt tmp päähakemistoa ei ole vielä
    mkdir -p $temppiHakemisto
fi
olemAlihak=$(ls $temppiHakemisto|tail -n 1) #katsotaan mikä on suurin olemassaoleva alihakemisto
luoAlihak=$(expr $olemAlihak + 1) #alihakemisto lukuarvona olemassaoleva suurin + 1
tmluoAlihak="0000"$luoAlihak
sluoAlihak=${tmluoAlihak: -4}
temppiHakemisto=$temppiHakemisto/$sluoAlihak #on nyt muodossa /tmp/dvbteksti2srt/0001 (-9999)
mkdir $temppiHakemisto
#***********************************************************************************************************************
touch $temppiHakemisto/loki.txt 2>/dev/null
if [[ $? != "0" ]];then
    echo "Tarkista $temppiHakemisto käyttöoikeus. Seis."
    exit
fi


lcall=$LC_ALL #otetaan talteen jos onkin määritelty niin voidaan palauttaa samaksi
export LC_ALL=C #ccextractorin koodissa bugin, vaatii tän
echo "Suoritetaan ccextractor, tässä menee hetki..."
ccextractor -dvblang $kieli -out=spupng -o $temppiHakemisto/$projektiNimi.xml -noteletext "$vtiedosto" >>$temppiHakemisto/loki.txt

# *******************************  KÄSITELLÄÄN KUVIA NIIN ETTÄ OCR ONNISTUU PAREMMIN *****************
mkdir -p $temppiHakemisto/muokatutKuvat
rm -rf $temppiHakemisto/muokatutKuvat/*
cd $temppiHakemisto/$projektiNimi.d/

echo "Käsitellään:"
for kuva in *.png
do
    numero=$(echo $kuva|cut -c 4-7)
    echo -ne "$kuva\033[0K\r"
    convert $kuva $convertParametrit $temppiHakemisto/muokatutKuvat/$numero.png >>$temppiHakemisto/loki.txt
    tesseract $tessekieli  $temppiHakemisto/muokatutKuvat/$numero.png $temppiHakemisto/muokatutKuvat/$numero >>$temppiHakemisto/loki.txt 2>/$temppiHakemisto/tessaerr.txt #OCR yksittäisestä kuvasta yksittäiseksi txt-tiedostoksi
    cat $temppiHakemisto/muokatutKuvat/$numero.txt >> $temppiHakemisto/muokatutKuvat/_teksti.txt #debuggia
done
echo ""

cd $omaSijainti #palataan sinne mistä skripti käynnistettiin
export LC_ALL=$lcall #palautetaan tämä siksi mikä se olikin eli luultavimmin tyhjä TÄRKEÄ PALAUTTAA ENNEN PYTHONIA!
echo "Luodaan SRT-tiedosto"
luosrt.py "$temppiHakemisto" "$projektiNimi" #kutsutaan python skriptiä, joka yhdistelee ocr-tulkatut tekstit srt-tiedostoksi. 
filename=$(basename "$vtiedosto")
#extension=${filename##*.}
filename=${filename%.*}

cp $temppiHakemisto/tekstit.srt "$filename.srt"
if [[ $? != "0" ]];then
    echo "Jotain meni pieleen. Seis."
    exit
fi

echo "Tekstitystiedosto luotu: "$omaSijainti/$filename.srt
#rm -rf $temppiHakemisto

