#!/bin/bash
#sudo apt -y install omgrip lsdvd (plus ne jotka dvbteksti2srt tarttee)
#
# esimerkki joka mounttaa DVD:n iso-kuvan ja rippaa siitä suomenkieliset tekstit srt-tiedostoksi
# suorita ./purateksti hakemistossa jossa DVD .iso sijaitsee
# suoritushakemistoon tulee tekstitykset.txt jotka nyt on vielä ilman ajoituksia
# jättää kaikki paskat siivoamatta subit-alihakemistoon
#

palaaHakemistoon=$(pwd)
sudo mkdir -p /media/loop
sudo mount -t iso9660 -o loop *.iso /media/loop #eli suoritetaan tää skripti hakemistossa jossa dvd:n iso-kuva on.
subraita=$(lsdvd -s  /media/loop/video_ts/|grep 'Language: fi' |cut -d ":" -f 2|cut -c 2-3) #etsitään fin-raidan numero
subraita=$(echo $subraita - 1|bc) #mplayer aloittaa numeroinnin nollasta kun lsdvd ykkösestä
pisinTitle=$(lsdvd /media/loop/video_ts/ |grep Long|cut -d ":" -f 2|cut -c 2-)

echo Pisin Title $pisinTitle
echo tekstitysraita $subraita

rm -rf subit
mkdir -p subit
cd subit

for tiedosto in /media/loop/video_ts/vts_$pisinTitle*.vob ;do #tää on aivan paska tapa ja tulee ongelmia kun kaikissa ei ole menuja...
    numero=$(echo $tiedosto|cut -d '_' -f 4|cut -d '.' -f 1) # "/media/loop/video_ts/vts_01_4.vob" ja tästä halutaan "4"
    if [[ $numero != 0 ]]; then # jos ei ole /media/loop/video_ts/vts_01_0.vob
        mkdir $numero
        mencoder $tiedosto -nosound -ovc frameno -o /dev/null -vobsuboutindex 0 -sid $subraita -vobsubout $numero/teksti
        subp2png -n $numero/teksti #-n, --normalize             Normalize the palette
    fi
done

#sitten käsitellään kuvat helpommin ocr-luettavaan muotoon ja tunnistetaan:
#convertParametrit="-resize 300% -negate -alpha remove -background black" tää ei toimi tässä

#tesseract ei tunnista jos lyhyt teksti puolessa välissä kuvaa isoilla kirjaimilla.
#kierretään ongelma trimmaamalla kuvasta tyhjät pois. ja lisäämällä mustat palkit sivuille ja hieman ylös
#ja alaskin. ne muuttuu negatessa valkoiseksi ja tunnistus onnistuu
#
convertParametrit="-trim -bordercolor black -border 50x5 -resize 150% -negate -alpha remove -background black"
tessekieli="-l fin"

echo käsitellään kuvaa:
for dir in */ ; do #käydään alihakemistot läpi
    cd $dir
    mkdir -p kasitellyt tekstit
    for kuva in *.png ; do
        numero=$(echo $kuva|cut -c 7-10) #teksti0012.png --> 0012
        echo -ne "$kuva\033[0K\r"
        convert $kuva $convertParametrit kasitellyt/$numero.png >/dev/null 2>/dev/null
        tesseract $tessekieli  kasitellyt/$numero.png tekstit/$numero 2>/dev/null
    done
    cd ..
done
echo tehty

#nyt tiedostot on alihakemistoissaan omina tekstitiedostoinaan. ne pitäisi sitten yhdistää ja ajoittaa
#mutta nyt vain kootaan ne tekstitiedostoksi ilman ajoituksia:

rm -rf $palaaHakemistoon/tekstitykset.txt
for dir in */ ; do #käydään alihakemistot läpi
    echo ------------------------- $dir -------------- >>$palaaHakemistoon/tekstitykset.txt
    cd $dir"tekstit"
    for teksti in *.txt ; do
        #echo dir: $dir teksti: $teksti pwd: $(pwd)
        cat $teksti |sed 's/\x0C//g' |sed 's/\x0A//g' >>$palaaHakemistoon/tekstitykset.txt
    done
    cd ../..
done

