#!/bin/bash

#Varmistetaan että myöhemmin lisätyt riippuvuudet täyttyy
array=( tesseract-ocr-swe tesseract-ocr-fin python3-pip git build-essential git automake cmake libcurl4-gnutls-dev tesseract-ocr libtesseract-dev libleptonica-dev imagemagick ogmrip lsdvd mencoder mediainfo ffmpeg )
for i in "${array[@]}"
do
    onkoAsennettu=$(dpkg-query --show --showformat='${db:Status-Status}\n' $i 2>/dev/null)
    if [ "$onkoAsennettu" != "installed" ]; then
        echo "Installing package $i"
        sudo apt install -y $i
    fi
done

chmod a+x dvbteksti2srt luosrt.py
sudo cp dvbteksti2srt luosrt.py /usr/bin
if [[ $? != "0" ]];then
    echo "Jotain meni pieleen. Seis."
    exit
fi
echo "Päivitys ok"




#ogmrip lsdvd mencoder mediainfo ffmpeg
